In [1]:
%load_ext autoreload
%autoreload 2

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

In [2]:
import pandas as pd

import sys
current_working_dir = os.getcwd()
# get the path to directory "pe_granular_analysis"
_path = current_working_dir[:current_working_dir.find("pe_granular_analysis")+len("pe_granular_analysis")]
if _path not in sys.path:
    sys.path.append(_path)

from preprocessing.nifti_conversion import batch_convert_dicom_to_volume
from preprocessing.dataframe_formatter import dataframe_norm
from preprocessing.segmentation import segmentator_process, CustomSegmentator
from preprocessing.segmentation import segmentation2bbox_batch_process
from preprocessing.dataframe_formatter import add_path2df

from configs.pe.pe_final import PELabelMask

from explainer.utils.visualize_cam import overlap_cam_on_voxel
from utils.data_visualizer import ColorImageSliceViewer3D
from utils.base import format_input_path

from tqdm import tqdm

import gc

import numpy as np
import torch
torch.backends.cudnn.enabled = False

/home/zhu/.conda/envs/cp310env/lib/python3.10/site-packages/albumentations/__init__.py:24: UserWarning: A new version of Albumentations is available: 2.0.8 (you have 1.4.21). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

In [3]:
# build/load your dataframe here
example_data_dir = os.path.join(_path, "data")
example_output_dir = os.path.join(_path, "temp")

example_pid = None
example_study_uid_1 = "7f6fb39566ed"
example_series_uid_1 = "b34edb1a4de7"

example_study_uid_2 = "00268ff88746"
example_series_uid_2 = "75d23269adbd"

df = pd.DataFrame([
    {
        "PatientID": None,
        "StudyInstanceUID": example_study_uid_1,
        "SeriesInstanceUID": example_series_uid_1,
    },
    {
        "PatientID": None,
        "StudyInstanceUID": example_study_uid_2,
        "SeriesInstanceUID": example_series_uid_2,
    },
])

In [ ]:
err_suids = batch_convert_dicom_to_volume(
    df=df,
    source_folder=example_data_dir,
    output_folder=example_output_dir,
)
if len(err_suids) > 0:
    print("Errors occurred during DICOM to volume conversion:")
    for error in err_suids:
        print(error)
else:
    print("DICOM to volume conversion completed successfully.")

In [ ]:
cs = CustomSegmentator(task="lung", device="cuda")
for _, row in tqdm(df.iterrows(), total=df.shape[0]):
    _pid = row["PatientID"] if "PatientID" in row else None
    _study_uid = row["StudyInstanceUID"] if "StudyInstanceUID" in row else None
    _series_uid = row["SeriesInstanceUID"] if "SeriesInstanceUID" in row else None
    error = segmentator_process(
        segmentator_instance=cs,
        input_folder=example_output_dir,
        pid=_pid,
        study_uid=_study_uid,
        series_uid=_series_uid,
    )
    if error is not None:
        print(f"Error occurred during segmentation for SeriesInstanceUID: {_series_uid}")

In [6]:
df = segmentation2bbox_batch_process(df, task="lung", input_folder=example_output_dir, save_path=example_output_dir)
df = add_path2df(df, path=example_output_dir)
df.to_csv(os.path.join(example_output_dir, "lung_labels_bbox_with_path.csv"), index=False)
df

Segmentation2BBOX Progress: 100%|██████████| 2/2 [00:01<00:00,  1.43it/s]

Saving segmentation bounding boxes to /home/zhu/github/pe_granular_analysis/temp/lung_labels_bbox.csv

,PatientID,StudyInstanceUID,SeriesInstanceUID,lung,image_folder
0,None,7f6fb39566ed,b34edb1a4de7,"[39, 126, 12, 483, 414, 167]",/home/zhu/github/pe_granular_analysis/temp/7f6...
1,None,00268ff88746,75d23269adbd,"[78, 155, 42, 405, 394, 216]",/home/zhu/github/pe_granular_analysis/temp/002...

In [ ]:
cfg = PELabelMask()
cfg.ddp = False
cfg.img_size = 384 # 256 used in training
cfg.working_dir = example_output_dir
cfg.test_result_dir = example_output_dir
cfg.on_deploy = True
cfg.on_grad_cam = False
print(cfg)

In [8]:
dataset_instance = cfg.dataset_class(dataframe=df, usage="inference", config=cfg)
data_loader = torch.utils.data.DataLoader(
    dataset_instance,
    batch_size=1, # or more if memory allows
    shuffle=False,
    num_workers=0, # set to 0 for debugging, increase for speed if needed
    pin_memory=True,
    drop_last=False,
)

Inference/cam mode: No labels will be returned.

In [ ]:
model_settings = cfg.get_model_setups()

model = cfg.model_class(**model_settings)

weights_path = os.path.join(
    _path,
   "models/weights/example_weight.pth"
)
model.custom_load_from_checkpoint(weights_path)
model = model.cuda()
model.eval()

In [10]:
predictions = []
with torch.no_grad():
    for batch in data_loader:
        input_images = batch["images"].cuda()
        outputs = model(input_images)
        prediction = torch.sigmoid(outputs).cpu().numpy()
        predictions.append(prediction)

# flatten the list of predictions
predictions = np.vstack(predictions).reshape(-1)
# attach predictions to the dataframe
df['pe_present_in_exam'] = predictions
df

,PatientID,StudyInstanceUID,SeriesInstanceUID,lung,image_folder,pe_present_in_exam
0,None,7f6fb39566ed,b34edb1a4de7,"[39, 126, 12, 483, 414, 167]",/home/zhu/github/pe_granular_analysis/temp/7f6...,0.945079
1,None,00268ff88746,75d23269adbd,"[78, 155, 42, 405, 394, 216]",/home/zhu/github/pe_granular_analysis/temp/002...,0.156157

In [ ]:
from explainer.explain_pipeline import explain
from explainer.configs.explainer_cfg import ExplainerConfig

explain_cfg = ExplainerConfig(dev_cfg=cfg)

model_weight_paths = os.path.join(
    _path,
   "models/weights/ultimate.pe.aug.pth"
)
cases_to_explain = df
test_name = "cam_test"

explain(cfg=explain_cfg, model_weight_paths=model_weight_paths, cases_to_explain=cases_to_explain, test_name=test_name)